apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: maks1mka/gateway:latest
        resources:
          requests:
            cpu: 700m
            memory: 700Mi
          limits:
            cpu: 700m
            memory: 700Mi
        readinessProbe: 
          initialDelaySeconds: 15 
          periodSeconds: 30 
          httpGet: 
            path: /actuator/health/readiness
            port: 8083
            scheme: HTTP 
          timeoutSeconds: 2 
          failureThreshold: 1 
          successThreshold: 1
        livenessProbe: 
          initialDelaySeconds: 30 
          periodSeconds: 30 
          httpGet: 
            path: /actuator/health/liveness
            port: 8083
            scheme: HTTP 
          timeoutSeconds: 5 
          failureThreshold: 10 
          successThreshold: 1
        ports:
        - containerPort: 8083
