apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cG9zdGdyZXM=
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMzUuMjI4LjEwMi4yMzI6NTQzMi9wb3N0Z3Jlcw==
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=