apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.0.0
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 8089
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "8089"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
