apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visit-service
  template:
    metadata:
      labels:
        app: visit-service
    spec:
      containers:
      - name: visit-service
        image: maks1mka/visit-service:latest
        resources:
          requests:
            cpu: 300m
            memory: 700Mi
          limits:
            cpu: 300m
            memory: 701Mi
        ports:
        - containerPort: 8085
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_PASSWORD
