spring:
  application:
    name: book-service
    book-files-directory: "C:/Users/maksi/Desktop/Новая папка/statics/"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


server:
  port: 8084


eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8081/eureka"
