spring:
  application:
    name: user-service
    users-profiles-directory: "app/statics/"
  services:
    book-service-url: http://book-service:8084
    auth-service-url: http://auth-service:8082
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  kafka:
    bootstrap-servers: kafka:9092
    topics:
      status-update: "status-update"
      status-create: "status-create"
      status-delete: "status-delete"
      like-create: "like-create"
      like-delete: "like-delete"
      new-visit: "new-visit"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    admin:
      auto-create: true
      properties:
        replication-factor: 1
        num-partitions: 3

server:
  port: 8086

