apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service
        image: maks1mka/review-service:latest
        resources:
          requests:
            cpu: 300m
            memory: 700Mi
          limits:
            cpu: 300m
            memory: 700Mi
        readinessProbe: 
          initialDelaySeconds: 15 
          periodSeconds: 30 
          httpGet: 
            path: /actuator/health/readiness
            port: 8083
            scheme: HTTP 
          timeoutSeconds: 2 
          failureThreshold: 1 
          successThreshold: 1
        livenessProbe: 
          initialDelaySeconds: 30 
          periodSeconds: 30 
          httpGet: 
            path: /actuator/health/liveness
            port: 8083
            scheme: HTTP 
          timeoutSeconds: 5 
          failureThreshold: 10 
          successThreshold: 1
        ports:
        - containerPort: 8084
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_PASSWORD
