apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: book-service
        image: maks1mka/user-service:latest
        resources:
          requests:
            cpu: 700m
            memory: 700Mi
          limits:
            cpu: 700m
            memory: 700Mi
        readinessProbe: 
          initialDelaySeconds: 15 
          periodSeconds: 30 
          httpGet: 
            path: /actuator/health/readiness
            port: 8086
            scheme: HTTP 
          timeoutSeconds: 2 
          failureThreshold: 1 
          successThreshold: 1
        livenessProbe: 
          initialDelaySeconds: 30 
          periodSeconds: 30 
          httpGet: 
            path: /actuator/health/liveness
            port: 8086
            scheme: HTTP 
          timeoutSeconds: 5 
          failureThreshold: 10 
          successThreshold: 1
        ports:
        - containerPort: 8086
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_PASSWORD
