spring:
  application:
    name: review-service
  datasource:
    url: "jdbc:postgresql://192.168.196.213:5432/postgres"     #  host.docker.internal
    username: "postgres"
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:8090
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 3
    topics:
      changes: review-changes


server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: "http://eureka-server:8081/eureka"
